import { useGlobal } from '@/context/Global';
import { cn } from '@/utils/cn';
import Link from 'next/link';
import { useCallback, useState } from 'react';
import { IconClose, IconRedirectOutside } from '../Icons';
import type { SectionData } from './section';
import Section from './section';

interface RulesModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const RulesModal = ({ isOpen, onClose }: RulesModalProps) => {
  const [isVisible, setIsVisible] = useState(isOpen);
  const { setRulesModalOpen } = useGlobal();

  const data: SectionData[] = [
    {
      title: '<strong>How to Trade on ShaftKings</strong>',
      description:
        'In <strong>ShaftKings</strong>, users trade based on predictions about future cricket events. Most of our market questions are based on <strong>YES </strong> and <strong>NO</strong> predictions, but some are specific team names, countries or alphanumeric options which you can select. <br/> <br/> For <strong>YES or NO</strong> markets, you can choose depending on your expectations:',
      subDescription: [
        {
          title:
            '<span class="text-shaftkings-green-200  items-center gap-x-1 list-item font-medium"> YES</span>',
          description:
            ": Predict the event will happen. If you're right, you’ll earn rewards based on your prediction and market dynamics.",
        },
        {
          title:
            '<span class="text-shaftkings-red-200  items-center gap-x-1 list-item font-medium"> NO</span>',
          description:
            ': Predict the event will not happen. If correct, you’ll receive rewards based on the final outcome.',
        },
      ],
    },
    {
      title: '<strong>Market Resolution</strong>',
      description:
        'All markets resolve on a 1:1 basis, ensuring fairness and transparency. The source of primary information will be <a href="https://www.espncricinfo.com" target="_blank" rel="noopener noreferrer" class="text-shaftkings-gold-200 underline">www.espncricinfo.com</a> which is the world’s leading website for cricket scores and data. All markets will resolve based on the information provided on this website. <a href="https://cricket.cricket" target="_blank" rel="noopener noreferrer" class="text-shaftkings-gold-200 underline">ShaftKings</a> takes no responsibility for the accuracy of information displayed on 3rd party websites such as <a href="https://www.espncricinfo.com" target="_blank" rel="noopener noreferrer" class="text-shaftkings-gold-200 underline">espncricinfo.com</a>.',
      subtitle: '',
    },
    {
      title: '<strong>Understanding the Percentages</strong>',
      description:
        'The percentages displayed are generated by our Auto Market Maker (AMM) and indicate:',
      subDescription: [
        {
          title: '',
          description:
            '<span class="list-item text-shaftkings-dark-150"><span class="text-white">The implied probability of each outcome.</span></span>',
        },
        {
          title: '',
          description:
            '<span class="list-item text-shaftkings-dark-150"><span class="text-white">How liquidity and trading activity are distributed across the market.</span></span>',
        },
      ],
      subtitle:
        'A higher probability means <strong>lower potential returns</strong> when you’re correct. Always review the percentages to understand your <strong>risk-to-reward</strong> balance.',
    },
    {
      title: '<strong>When Will I Receive My Winnings?</strong>',
      description:
        'Your winnings will land in your profile within <strong>24–48</strong> hours of the event’s conclusion. You can cash out once you’ve earned at least <strong>$5 USDC</strong>. We’re working hard to bring you instant payouts soon!',
      subtitle: '',
    },
    {
      title: '<strong>More Details</strong>',
      description:
        '📢 Stay Updated 🔗 Follow us for updates: <a href="https://x.com/cricdotcric" target="_blank" rel="noopener noreferrer" class="text-shaftkings-gold-200 underline">X Corp</a> & <a href="https://www.linkedin.com/company/cricketdotcricket/about/" target="_blank" rel="noopener noreferrer" class="text-shaftkings-gold-200 underline">LinkedIn</a>',
      subtitle: '',
    },
  ];

  const handleClose = useCallback(() => {
    const modalElement = document.querySelector('.modal');
    const overlayElement = document.querySelector('.overlay');

    const finishClose = () => {
      setIsVisible(false);
      setRulesModalOpen(false);
      onClose();
    };

    if (modalElement && overlayElement) {
      modalElement.classList.add('modal-exit');
      overlayElement.classList.add('overlay-exit');

      modalElement.addEventListener('animationend', finishClose, {
        once: true,
      });
    } else {
      finishClose();
    }
  }, [onClose, setRulesModalOpen]);

  if (!isVisible) return null;

  return (
    <>
      <div
        onClick={handleClose}
        className="overlay overlay-enter fixed inset-0 z-50 w-full bg-black/30 backdrop-blur-xl transition-opacity"
        aria-hidden="true"
      />
      <div
        className={cn(
          'modal modal-enter fixed right-0 top-0 z-[99] h-full w-full lg:w-[400px] flex flex-col',
          'border-l border-[#FFFFFF29] bg-white dark:bg-[#FFFFFF14] backdrop-blur-3xl',
          'rounded-tl-md transition-transform duration-300 ease-in-out'
        )}
      >
        <div className="shrink-0 px-4 pt-6">
          <div className="relative">
            <h2 className="mb-3 text-lg font-semibold text-black dark:text-white">
              Details and Rules
            </h2>
            <time className="text-xs italic text-[#C0C0C0]">
              Updated on January 13, 2025
            </time>
            <button
              onClick={handleClose}
              className="absolute right-0 top-0 rounded-full bg-[#FFFFFF29] p-1 transition-colors duration-200"
              aria-label="Close"
            >
              <IconClose />
            </button>
          </div>
        </div>
        <div className="mt-2 h-[calc(100%-140px)] overflow-y-auto p-4 lg:mt-0 min-[1920px]:h-full">
          {data.map((section, index) => (
            <Section
              key={index}
              title={section.title}
              description={section.description}
              subDescription={section.subDescription}
              subtitle={section.subtitle}
            />
          ))}
        </div>
        <div className="absolute bottom-0 left-0 flex h-9 w-full items-center justify-between border border-white/5 bg-black/10 px-4 dark:bg-white/10">
          <p className="text-xs font-medium dark:text-white">
            For further details, check out our documentation
          </p>
          <Link
            href="https://docs.triadfi.co/"
            target="_blank"
            aria-label="Open documentation"
          >
            <IconRedirectOutside />
          </Link>
        </div>
      </div>
    </>
  );
};

export default RulesModal;
