const Rules = () => {
  return (
    <div className="mx-auto mt-10 w-full max-w-[1200px] px-2.5 pb-[100px] lg:px-0">
      <h4 className="mb-4 text-2xl font-bold text-white">Referral Rules</h4>
      <div className="space-y-4 text-sm text-gray-700 dark:text-gray-300">
        <ul className="flex flex-col gap-y-3 pl-5 text-sm text-[#A1A7BB]">
          <li>
            1. Referral and Commission Mechanism: Users who sign up using the
            referrer’s unique link or code will generate commissions for the
            referrer with every valid trade made on Cricket.
          </li>
          <li>
            2. Commission Rate: The referrer can earn up to 50% of the trading
            fees generated by their referrals.
          </li>
          <li>
            3. How to Participate:
            <ul className="mt-4 flex list-disc flex-col gap-y-4 pl-5">
              <li>
                Click the button on the event page to activate your referral
                link.
              </li>
              <li>
                Share your link with friends and track your earnings directly on
                the referral dashboard.
              </li>
            </ul>
          </li>
          <li>
            4. Reward Distribution:
            <ul className="mt-4 flex list-disc flex-col gap-y-4 pl-5">
              <li>Rewards are distributed daily at 00:00 UTC.</li>
              <li>Commission payments are made in USDC.</li>
              <li>
                The amount received is calculated based on the net trading fees
                generated by referrals.
              </li>
            </ul>
          </li>
          <li>
            5. The following activities are not eligible for commission rewards:
            <ul className="mt-4 flex list-disc flex-col gap-y-4 pl-5">
              <li>
                Transactions deemed suspicious or involving volume manipulation.
              </li>
              <li>Any activity that violates the platform’s rules.</li>
            </ul>
          </li>
          <li>
            6. Compliance and Risk Control:
            <ul className="mt-4 flex list-disc flex-col gap-y-4 pl-5">
              <li>
                Self-referrals are prohibited: Using multiple accounts to refer
                yourself is strictly forbidden. If detected, users will lose
                their reward eligibility, and any benefits obtained will be
                considered invalid.
              </li>
              <li>
                Cricket reserves the right to adjust the program’s rules as
                necessary to maintain integrity and security.
              </li>
            </ul>
          </li>
          <li>
            7. Valid Referral Requirements (within 7 days of signup):
            <ul className="mt-4 flex list-disc flex-col gap-y-4 pl-5">
              <li>
                a) Cricket reserves the right to interpret and modify the
                referral program rules at any time as necessary.
              </li>
              <li>
                b) Maintain a minimum level of activity on the platform during
                the initial period.
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  );
};

export default Rules;
